In [1]:
import numpy as np
import pandas as pd

Mage Duel!
Let's use what we've learned to play a mage duel!

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

Exercises
Simulate mage duels to answer who is the more powerful mage?

- Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.
- Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?
- Do the results change much at 100 duels?
Now, simulate 10,000 mage duels. Is there a clear winner?

In [93]:
d4 = [1, 2, 3, 4]
d6 = [1, 2, 3, 4, 5, 6]

Hypothesis: I win most of the time, more chances of rolling highest numbers on die

In [112]:
n_simulations = 10000

In [131]:
your_health = np.random.choice(d4, size=(n_simulations, 6))
your_spell = np.random.choice(d4, size=(n_simulations, 6))

enemy_health = np.random.choice(d6, size=(n_simulations, 4))
enemy_spell = np.random.choice(d6, size=(n_simulations, 4))

your_health.sum(axis=1), your_spell.sum(axis=1), enemy_health.sum(axis=1), enemy_spell.sum(axis=1)

(array([13, 14, 11, ..., 15, 12, 16]),
 array([16, 17, 19, ..., 13, 15, 10]),
 array([15, 16, 18, ..., 11, 10, 16]),
 array([13,  5, 17, ..., 17, 17, 11]))

In [151]:
you_win = (your_spell.sum(axis=1) >= enemy_health.sum(axis=1) | (enemy_spell.sum(axis=1) <= your_health.sum(axis=1)))

In [152]:
you_win.mean()

0.6044

In [149]:
enemy_win = (enemy_spell.sum(axis=1) >= your_health.sum(axis=1) | (your_spell.sum(axis=1) <= enemy_health.sum(axis=1)))

In [150]:
enemy_win.mean() 

0.4301