In [2]:
import numpy as np
import pandas as pd

1. How likely is it that you roll doubles when rolling two dice?


In [3]:
first_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
second_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
first_die, second_die

(array([1, 6, 1, ..., 2, 2, 1]), array([5, 1, 2, ..., 1, 3, 6]))

In [4]:
(first_die == second_die).mean()

0.16795

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?


In [5]:
# 1 = heads, 0 = tails
outcomes = [1, 0]

In [6]:
flips = np.random.choice(outcomes, size=(10_000, 8))
flips

array([[0, 0, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1]])

In [7]:
n_of_heads = flips.sum(axis=1)
n_of_heads

array([3, 7, 6, ..., 4, 4, 4])

In [8]:
(n_of_heads == 3).mean()

0.2201

In [9]:
(n_of_heads > 3).mean()

0.6325

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?


In [10]:
# trials = 2
# web dev = 1, ds = 0
outcomes = [1, 1, 1, 0]

billboard_outcome = np.random.choice(outcomes, size=(1_000_000, 2))

billboard_outcome

array([[1, 1],
       [0, 0],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

In [11]:
ds_only_billboards = billboard_outcome.sum(axis=1)

In [12]:
(ds_only_billboards == 0).mean()

0.062337

4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?



In [13]:
# Monday = 17
# Mean = 3
# STDDEV = 1.5
# Friday = ??

In [14]:
ndays = ncols = 5
nsimulations = 10_000

In [15]:
daily_poptart_consumption = np.random.normal(loc=3, scale=1.5, size=(1_000_000, 5))

In [16]:
weekly_poptart_consumption = daily_poptart_consumption.sum(axis=1)
weekly_poptart_consumption

array([12.90777086, 15.98709521, 14.45195246, ..., 12.84415907,
       14.44318673, 17.08582799])

In [17]:
(weekly_poptart_consumption <= 16).mean()

0.616038

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?


In [18]:
# men_avg_h = 178, men_sd = 8
# women_avg_h  = 170, women_sd = 6

random_man_h = np.random.normal(loc=178, scale=8, size=(1_000_000))
random_woman_h = np.random.normal(loc=170, scale=6, size=(1_000_000))

In [19]:
manh_minus_womanh = random_man_h - random_woman_h
manh_minus_womanh

array([  3.96183356,  14.90519842,  10.71296045, ..., -14.24037955,
         2.59672609,   0.15666313])

In [20]:
(manh_minus_womanh < 0).mean()

0.212447

6a. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?


In [21]:
# Probability of failure = 1 / 250 = 0.004

fifty_chances = np.random.binomial(50, 0.004, 10_000)

In [22]:
(fifty_chances == 0).mean()

0.8178

In [23]:
one_hundred_chances = np.random.binomial(100, 0.004, 10_000)

In [24]:
(one_hundred_chances == 0).mean()

0.6653

6b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?


In [25]:
one_fifty = np.random.binomial(150, 0.004, 10_000)

In [26]:
(one_fifty > 0).mean()

0.4507

6c. How likely is it that 450 students all download anaconda without an issue?


In [27]:
four_fifty = np.random.binomial(450, 0.004, 10_000)

In [28]:
(four_fifty == 0).mean()

0.1678

7a. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [29]:
# p = .7

In [30]:
three_days = np.random.binomial(3, 0.7, 1_000_000)

In [31]:
(three_days == 0).mean()

0.027322

7b. How likely is it that a food truck will show up sometime this week?

In [32]:
one_week = np.random.binomial(7, 0.7, 1_000_000)

In [33]:
(one_week >= 1).mean()

0.999811

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?`

In [34]:
days = [*range(1, 366, 1)]

In [51]:
birthdays_of_people = np.random.choice(days, size=(1_000_000, 23))
birthdays_of_people

array([[109,  67, 298, ..., 164, 230, 261],
       [257, 209, 184, ..., 191, 344,  63],
       [345, 230, 212, ..., 358, 114, 248],
       ...,
       [210, 134, 226, ..., 278,  10, 331],
       [350, 197, 195, ..., 138,   7,   8],
       [154, 191, 197, ..., 292,   7, 101]])

In [52]:
df = pd.DataFrame(birthdays_of_people)

In [53]:
unique_counts = pd.Series(df.nunique(axis=1))

In [54]:
(unique_counts < 23).mean()

0.506812

In [64]:
birthdays_of_people2 = np.random.choice(days, size=(1_000_000, 20))

In [60]:
df2 = pd.DataFrame(birthdays_of_people2)

In [61]:
unique_counts2 = pd.Series(df2.nunique(axis=1))

In [62]:
(unique_counts2 < 20).mean()

0.411603

In [66]:
birthdays_of_people3 = np.random.choice(days, size=(1_000_000, 40))

In [67]:
df3 = pd.DataFrame(birthdays_of_people3)

In [68]:
unique_counts3 = pd.Series(df3.nunique(axis=1))

In [69]:
(unique_counts3 < 40).mean()

0.89106